spring.application.name=FlightCust

server.port=${PORT:8098}

spring.datasource.url=${jdbc:postgresql://booking:9nGrhCAZqvqLmyqJJLvlAXFUqpjY8om0@dpg-d81g0v7avr4c73bc61r0-a/booking_9sh1}
spring.datasource.username=${booking}
spring.datasource.password=${9nGrhCAZqvqLmyqJJLvlAXFUqpjY8om0}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true